name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "initial_commit" ]
    # branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint-job:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Check styling and linting
        run: dotnet format --verbosity normal --severity warn --verify-no-changes Keyboardtester/KeyboardTester.sln
     
  build-and-test-job:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Restore all projects
        run: dotnet restore Keyboardtester/KeyboardTester.sln
      - name: Build solution
        run: dotnet build Keyboardtester/KeyboardTester.sln --no-restore
      - name: Save current UTC time as an environment variable
        run: |
          "utc_date=$(date +'%Y%m%d%H%M%S')" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Run unit tests
        run: dotnet test Keyboardtester/UnitTests/UnitTests.csproj --no-build --logger "html;LogFileName=TestResults_$env:utc_date.html"
      - name: Upload test results to build
        uses: actions/upload-artifact@v3
        with:
          name: Test results
          path: KeyboardTester/UnitTests/TestResults/TestResults_${{ env:utc_date }}.html
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
