name: CD

on:
  # Triggers the workflow on pushing a tag that matches the pattern
  push:
    tags:
      - "v*.*"
# test
jobs:
  ci:
    name: CI
    uses: Ninc-Consulting/ninc_keyboard_tester/.github/workflows/github-ci.yml@initial_commit
  # lint:
  #   name: lint
  #   runs-on: windows-2019
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup dotnet
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: '6.0.x'
  #     - name: Check styling and linting
  #       run: dotnet format --verbosity normal --severity warn --verify-no-changes Keyboardtester/KeyboardTester.sln
  # build-and-test:
  #   name: build and test
  #   runs-on: windows-2019
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup dotnet
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: '6.0.x'
  #     - name: Restore all projects
  #       run: dotnet restore Keyboardtester/KeyboardTester.sln
  #     - name: Build solution
  #       run: dotnet build Keyboardtester/KeyboardTester.sln --no-restore
  #     - name: Run unit tests
  #       run: dotnet test Keyboardtester/UnitTests/UnitTests.csproj --no-build --logger "html"
  #     - name: Upload test results to build
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: Test results
  #         path: Keyboardtester/UnitTests/TestResults/
  #       # Use always() to always run this step to publish test results when there are test failures
  #       if: ${{ always() }}
  create-release:
    name: create release
    needs: [ ci ]
    runs-on: windows-2019
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Create standalone exe file
        run: dotnet publish KeyboardTester/KeyboardTesterApp/KeyboardTesterApp.csproj --self-contained --runtime win-x64 --output KeyboardTester/artifacts/
      - name: Create release and assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "KeyboardTester/artifacts/KeyboardTesterApp.exe"
