name: CD

on:
  push:
    tags:
      - "v*.*"
jobs:
  ci:
    name: CI
    uses: Ninc-Consulting/ninc_keyboard_tester/.github/workflows/github-ci.yml@initial_commit
  create-release:
    name: create release
    needs: [ ci ]
    runs-on: windows-2019
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Create standalone x64 exe file
        run: dotnet publish KeyboardTester/KeyboardTesterApp/KeyboardTesterApp.csproj --self-contained --runtime win-x64 --output KeyboardTester/artifacts/x64
      - name: Rename file
        run: ren KeyboardTester/artifacts/x64/KeyboardTesterApp.exe KeyboardTesterAppx64.exe
      - name: Create standalone x86 exe file
        run: dotnet publish KeyboardTester/KeyboardTesterApp/KeyboardTesterApp.csproj --self-contained --runtime win-x86 --output KeyboardTester/artifacts/x86
      - name: Rename file
        run: ren KeyboardTester/artifacts/x86/KeyboardTesterApp.exe KeyboardTesterAppx86.exe
      - name: Zip exe files
        uses: vimtor/action-zip@v1.1
        with:
          files: KeyboardTester/artifacts/x64/KeyboardTesterAppx64.exe KeyboardTester/artifacts/x86/KeyboardTesterAppx86.exe LICENSE README.md
          dest: KeyboardTester/artifacts/KeyboardTesterApp_${{ github.ref_name }}.zip
      - name: Create release and assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "KeyboardTester/artifacts/KeyboardTesterApp_${{ github.ref_name }}.zip"
